global_costmap:
  global_costmap:
    ros__parameters:
      # Common
      update_frequency: 1.0
      robot_base_frame: base_link
      map_subscribe_transient_local: true

      # Layers
      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        subscribe_to_updates: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      robot_base_frame: base_link
      transform_tolerance: 0.5

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: laser_scan_sensor
        laser_scan_sensor:
          topic: /scan
          max_obstacle_height: 0.5
          obstacle_range: 2.0
          raytrace_range: 3.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
